//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.18444
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilancioFenealgest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regionale.xlt")]
        public string ModelloRegionale {
            get {
                return ((string)(this["ModelloRegionale"]));
            }
            set {
                this["ModelloRegionale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SerachType {
            get {
                return ((int)(this["SerachType"]));
            }
            set {
                this["SerachType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("templateNazionale.xml")]
        public string FileFreeTemplate {
            get {
                return ((string)(this["FileFreeTemplate"]));
            }
            set {
                this["FileFreeTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InventarioScriviTipoInventario {
            get {
                return ((bool)(this["InventarioScriviTipoInventario"]));
            }
            set {
                this["InventarioScriviTipoInventario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InventarioScriviIntestazioniTipoInventario {
            get {
                return ((bool)(this["InventarioScriviIntestazioniTipoInventario"]));
            }
            set {
                this["InventarioScriviIntestazioniTipoInventario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int InventarioColonnaIniziale {
            get {
                return ((int)(this["InventarioColonnaIniziale"]));
            }
            set {
                this["InventarioColonnaIniziale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int InventarioRigaIniziale {
            get {
                return ((int)(this["InventarioRigaIniziale"]));
            }
            set {
                this["InventarioRigaIniziale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InventarioDisegnaOrizzontalmente {
            get {
                return ((bool)(this["InventarioDisegnaOrizzontalmente"]));
            }
            set {
                this["InventarioDisegnaOrizzontalmente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int InventarioRigheFraTipiInventario {
            get {
                return ((int)(this["InventarioRigheFraTipiInventario"]));
            }
            set {
                this["InventarioRigheFraTipiInventario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VisibilityTabPreventivo {
            get {
                return ((bool)(this["VisibilityTabPreventivo"]));
            }
            set {
                this["VisibilityTabPreventivo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RaiseChangeDataEvent {
            get {
                return ((bool)(this["RaiseChangeDataEvent"]));
            }
            set {
                this["RaiseChangeDataEvent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Conto nascosto")]
        public string HidedenContoCommmandText {
            get {
                return ((string)(this["HidedenContoCommmandText"]));
            }
            set {
                this["HidedenContoCommmandText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HiddenContoVisible {
            get {
                return ((bool)(this["HiddenContoVisible"]));
            }
            set {
                this["HiddenContoVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Noesis")]
        public string AppStyleName {
            get {
                return ((string)(this["AppStyleName"]));
            }
            set {
                this["AppStyleName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Feneal")]
        public string Header {
            get {
                return ((string)(this["Header"]));
            }
            set {
                this["Header"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Provinciale.xlt")]
        public string ModelloProvinciale {
            get {
                return ((string)(this["ModelloProvinciale"]));
            }
            set {
                this["ModelloProvinciale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int MaxColPrimaColonna {
            get {
                return ((int)(this["MaxColPrimaColonna"]));
            }
            set {
                this["MaxColPrimaColonna"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int MaxColSecondaColonna {
            get {
                return ((int)(this["MaxColSecondaColonna"]));
            }
            set {
                this["MaxColSecondaColonna"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("156")]
        public int MaxRowPrimaColonna {
            get {
                return ((int)(this["MaxRowPrimaColonna"]));
            }
            set {
                this["MaxRowPrimaColonna"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int MaxrowSecondaColonna {
            get {
                return ((int)(this["MaxrowSecondaColonna"]));
            }
            set {
                this["MaxrowSecondaColonna"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CreateFromTemplate {
            get {
                return ((bool)(this["CreateFromTemplate"]));
            }
            set {
                this["CreateFromTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("modello.xlt")]
        public string ModelloStampaTemplate {
            get {
                return ((string)(this["ModelloStampaTemplate"]));
            }
            set {
                this["ModelloStampaTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rendiconto.xls")]
        public string NomeFileDaSalvare {
            get {
                return ((string)(this["NomeFileDaSalvare"]));
            }
            set {
                this["NomeFileDaSalvare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Feneal di")]
        public string TestoProprietario {
            get {
                return ((string)(this["TestoProprietario"]));
            }
            set {
                this["TestoProprietario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InventarioFeneal {
            get {
                return ((bool)(this["InventarioFeneal"]));
            }
            set {
                this["InventarioFeneal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VisibilityTabStatoPatrimoniale {
            get {
                return ((bool)(this["VisibilityTabStatoPatrimoniale"]));
            }
            set {
                this["VisibilityTabStatoPatrimoniale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsFeneal {
            get {
                return ((bool)(this["IsFeneal"]));
            }
            set {
                this["IsFeneal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsRlst {
            get {
                return ((bool)(this["IsRlst"]));
            }
            set {
                this["IsRlst"] = value;
            }
        }
    }
}
