using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;

using BilancioFenealgest.ServiceLayer.DTO;
using WIN.BILANCIO.PresentationLogicComponents;

namespace BilancioFenealgest.UI.UIComponents
{
    public partial class FrmScrittureContoRLST : Form, IScrittureContoRLSTFormView
    {
        ScrittureContoRLSTPresenter _presenter;

        public FrmScrittureContoRLST()
        {
            InitializeComponent();
        }

        #region IScrittureFormView Membri di

        public bool IsLabelVisible
        {
            set { lblEmpty.Visible = value ; }
        }

        public string CaptionViewText
        {
            set { this.Text = value; }
        }

        public BilancioFenealgest.Middleware.IGridContainer<ScrittureDTO> GridContainer
        {
            get { return new DesktopGridContainer<ScrittureDTO>(dataGridView1, bindingSource1 ); }
        }

        
        public void SetPresenter(ScrittureContoRLSTPresenter presenter)
        {
            _presenter = presenter;
        }

      
        public bool ShowAndContinue()
        {
            return (base.ShowDialog() == DialogResult.OK);
        }

        #endregion

     

        #region IScrittureFormView Membri di


        public IScritturaSingolaContoRLSTFormView ScritturaSingolaView
        {
            get { return new FrmScritturaSingolaContoRLST(); }
        }

        #endregion

    

   

        #region IBasePresentation Membri di

        public BilancioFenealgest.Middleware.IMessageBox GetSimpleMessageNotificator()
        {
            return new DesktopMessageBox();
        }

        public BilancioFenealgest.Middleware.IOpenFileClass GetOpenFileDialog()
        {
            throw new NotImplementedException();
        }

        #endregion

     

        #region IScrittureFormView Membri di


        public string ElementiTrovati
        {
            set { lblNumero.Text = value; }
        }

        public bool IsMessaggioContoClassificazioneVisible
        {
            set { lblMessaggio.Visible = value; }
        }

        public bool IsAddScritturaEnabled
        {
            set { cmdAdd.Enabled = value; }
        }

        #endregion

      
  


        #region IScrittureFormView Membri di


        public bool CanFilterByDate
        {
            get { return chkDate.Checked ; }
        }

        public string CausaleFilter
        {
            get { return txtCausale.Text; }
        }

        public string PezzaFilter
        {
            get { return txtPezza.Text; }
        }

        public DateTime DateFromFilter
        {
            get { return dtpDa.Value.Date; }
        }

        public DateTime DateToFilter
        {
            get { return dtpA.Value.Date; }
        }

        public bool ViewAutogenerated
        {
            get { return chkAuto.Checked; }
        }

        #endregion

        private void chkDate_CheckedChanged(object sender, EventArgs e)
        {
            if (chkDate.Checked)
            {
                dtpDa.Enabled = true;
                dtpA.Enabled = true;
            }
            else
            {
                dtpDa.Enabled = false;
                dtpA.Enabled = false;
            }

        }

        #region IBasePresentation Membri di


        public BilancioFenealgest.Middleware.IOpenFileClass GetFolderBrowserDialog()
        {
            throw new NotImplementedException();
        }

        #endregion

  
        private void cmdFilter_Click_1(object sender, EventArgs e)
        {
            _presenter.Filter();
        }

        private void cmdCancelFilter_Click_1(object sender, EventArgs e)
        {
            _presenter.ReloadData();
        }

        private void cmdAdd_Click(object sender, EventArgs e)
        {
            _presenter.AddScrittura();
        }

        private void cmdRemove_Click(object sender, EventArgs e)
        {
            _presenter.RemoveScrittura();
        }

        private void cmdClose_Click_1(object sender, EventArgs e)
        {
            this.Close();
        }

     

        #region IScrittureContoRLSTFormView Membri di


        public string SaldoConto
        {
            set { lblMessaggio.Text = value; }
        }

        #endregion

        private void dataGridView1_CellMouseDoubleClick(object sender, DataGridViewCellMouseEventArgs e)
        {
            _presenter.ShowScrittura();
        }

        #region IScrittureContoRLSTFormView Membri di


        public bool IsWaitPanelVisible
        {
            set { panel2.Visible= value; }
        }

        public void NotifyTaskLabel(string text)
        {
            lblTask.Text = text;
        }

        public void HidePanel()
        {
            panel2.Visible=false;
        }

        #endregion

        private void button1_Click(object sender, EventArgs e)
        {
            _presenter.ExportToExcel();
        }
    }
}
