using System;
using System.Collections.Generic;
using System.Text;
using BilancioFenealgest.Middleware;
using BilancioFenealgest.ServiceLayer.DTO;
using WIN.BILANCIO.PresentationLogicComponents;
using System.Drawing;

namespace BilancioFenealgest.UI.PresentationLogicComponents
{
    public interface IScrittureFormView : IBasePresentation 
    {
        bool IsLabelVisible { set; }
        string CaptionViewText { set; }
        IGridContainer<ScrittureDTO> GridContainer {get;}
        void SetPresenter(ScritturePresenter presenter);

        IScritturaSingloaView ScritturaSingolaView { get; }

        IFrmTaglia FrmTagliaView { get; }
        void ShowContextMenu(object sender, Point location);
        void HideContextMenu();
        int SelectedRowsCount { get; }

        string Banca1 { get; }
        string Banca2 { get; }
        string Banca3 { get; }

        string Banca4 { get; }
        string Banca5 { get; }
        string Banca6 { get; }

        bool ShowAndContinue();

        void Dispose();

        string ElementiTrovati { set; }
        bool IsMessaggioContoClassificazioneVisible { set; }
        bool IsAddScritturaEnabled { set; }
        bool IsDuplicateScritturaEnabled { set; }

        bool CanFilterByDate { get; }
        string CausaleFilter { get; }
        string PezzaFilter { get; }
        DateTime DateFromFilter { get; }
        DateTime DateToFilter { get; }
        bool ViewAutogenerated { get; }
        ILookupList ComboEnte { get; }
        ILookupList ComboSettore { get; }
        ILookupList ComboPersonale { get; }


        object Invoke(Delegate method);
        object Invoke(Delegate method, params object[] args);
        bool IsWaitPanelVisible { set; }
        void NotifyTaskLabel(string text);
        void HidePanel();
        bool GroupByConto { get; }

        void SetScrittureTotalizzation(string totald );

        string MainHeader { get; }



        IFrmContoView ImportoFormView { get;  }

        bool IsSaldoInizialeEnabled { get; set; }
    }
}
