using System;
using System.Collections.Generic;
using System.Text;

namespace BilancioFenealgest.ServiceLayer
{
    public class ScrittureDTO
    {
        public string NumeroPezza { get; set; }
        public string Causale { get; set; }
        public bool AutoGenerated { get; set; }
        public string TipoOperazione { get; set; }
        public decimal Importo { get; set; }
        public string Id { get; set; }
        public DateTime Date { get; set; }
    }

}
